AllCops:
  Exclude:
    - 'bin/*'
    - 'db/*'
    - 'config/*'
    - 'Guardfile'
    - 'Rakefile'
  DisplayCopNames: true
# configures the length of a line or number of columns
Metrics/LineLength:
  Max: 200
Metrics/MethodLength:
  Include: ['app/controllers/*']
  Max: 150
Metrics/AbcSize:
  Include: ['app/controllers/*']
  Max: 30
Metrics/ClassLength:
  Max: 150
Metrics/BlockLength:
  ExcludedMethods: ['describe']

Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/For:
  Enabled: false
# configures guard clause for conditional statements
Style/GuardClause:
  Enabled: false


Layout/AlignHash:
  EnforcedColonStyle: key
Layout/ExtraSpacing:
  AllowForAlignment: false
Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented